# Generated by Django 5.1.2 on 2024-11-12 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_location_average_crowd_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchhistory',
            name='crowd_preference',
        ),
    ]
