# Generated by Django 5.1.2 on 2024-11-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_searchhistory_crowd_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='crowd_preference',
            field=models.FloatField(default=0),
        ),
    ]
